import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { createAuthStore, can } from '../src/core/auth/store.ts';
const password='Synthetic-test-password-42';
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'endo-auth-test-'));const path=join(dir,'auth.sqlite');const store=createAuthStore(path);t.after(()=>{store.close();rmSync(dir,{recursive:true,force:true});});const ceo=store.bootstrap('Dirección de prueba','ceo@example.com',password);return {store,ceo,path};}
function member(store,ceo,role='marketing'){const user=store.create(ceo.id,'Usuario de prueba',`${role}@example.com`,role);store.activate(store.issueToken(ceo.id,user.id),password);return user;}
test('bootstrap es único; identidad normalizada y contraseñas no están en texto plano',t=>{const {store,ceo,path}=fixture(t);assert.equal(store.needsSetup(),false);assert.throws(()=>store.bootstrap('Otro','otro@example.com',password));const db=new DatabaseSync(path);const row=db.prepare('SELECT password FROM users WHERE id=?').get(ceo.id);assert.notEqual(row.password,password);assert.match(row.password,/^[a-f0-9]{32}:[a-f0-9]{128}$/);db.close();assert.throws(()=>store.create(ceo.id,'Duplicado',' CEO@EXAMPLE.COM ','medico'));});
test('sesión aleatoria almacenada con hash; cierre de sesión invalida el token',t=>{const {store,path}=fixture(t);const token=store.login('ceo@example.com',password);assert.equal(store.session(token).role,'ceo');assert.equal(store.session('inventado'),null);const db=new DatabaseSync(path);assert.notEqual(db.prepare('SELECT token FROM sessions').get().token,token);db.close();store.logout(token);assert.equal(store.session(token),null);});
test('permisos por rol y denegación de administración a otro perfil',t=>{const {store,ceo}=fixture(t);for(const role of ['medico','enfermeria','administracion','marketing','paciente']){const user=member(store,ceo,role);const active=store.session(store.login(user.email,password));assert.equal(can(active,'portal'),true);assert.equal(can(active,'dashboard'),false);assert.equal(can(active,'accounts'),false);assert.throws(()=>store.list(user.id));assert.throws(()=>store.create(user.id,'Intruso','intruso@example.com','ceo'));}assert.equal(can(null,'accounts'),false);assert.equal(can(ceo,'accounts'),true);});
test('desactivación y cambios de rol revocan sesiones inmediatamente',t=>{const {store,ceo}=fixture(t);const user=member(store,ceo);const token=store.login(user.email,password);store.update(ceo.id,user.id,'marketing','inactive');assert.equal(store.session(token),null);assert.throws(()=>store.login(user.email,password));store.update(ceo.id,user.id,'medico','active');const fresh=store.login(user.email,password);store.update(ceo.id,user.id,'enfermeria','active');assert.equal(store.session(fresh),null);assert.throws(()=>store.update(ceo.id,ceo.id,'marketing','inactive'));});
test('activación de un solo uso; códigos renovados, vencidos e inactivos no funcionan',t=>{const {store,ceo,path}=fixture(t);const user=store.create(ceo.id,'Pendiente','pending@example.com','medico');const old=store.issueToken(ceo.id,user.id);const code=store.issueToken(ceo.id,user.id);assert.throws(()=>store.activate(old,password));store.activate(code,password);assert.throws(()=>store.activate(code,password));const expiring=store.issueToken(ceo.id,user.id);const db=new DatabaseSync(path);db.prepare('UPDATE tokens SET expires=0').run();db.close();assert.throws(()=>store.activate(expiring,password));const inactive=store.issueToken(ceo.id,user.id);store.update(ceo.id,user.id,'medico','inactive');assert.throws(()=>store.activate(inactive,password));});
test('recuperación revoca sesiones y sustituye la contraseña; sesiones vencidas son rechazadas',t=>{const {store,ceo,path}=fixture(t);const user=member(store,ceo);const token=store.login(user.email,password);const code=store.issueToken(ceo.id,user.id);assert.equal(store.session(token),null);store.activate(code,'New-synthetic-password-55');assert.throws(()=>store.login(user.email,password));const fresh=store.login(user.email,'New-synthetic-password-55');const db=new DatabaseSync(path);db.prepare('UPDATE sessions SET expires=0').run();db.close();assert.equal(store.session(fresh),null);});
test('intentos fallidos tienen límite y no permiten eludirlo variando mayúsculas',t=>{const {store}=fixture(t);for(let i=0;i<5;i++)assert.throws(()=>store.login('CEO@example.com','incorrecta'));assert.throws(()=>store.login('ceo@example.com',password),/15 minutos/);});
test('cuentas y auditoría persisten tras reabrir la base',t=>{const dir=mkdtempSync(join(tmpdir(),'endo-persist-test-'));const path=join(dir,'auth.sqlite');let store=createAuthStore(path);const ceo=store.bootstrap('Prueba','persist@example.com',password);store.close();store=createAuthStore(path);assert.equal(store.list(ceo.id).length,1);assert.equal(store.audit(ceo.id)[0].action,'initial_account');store.close();rmSync(dir,{recursive:true,force:true});});
