import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createAuthStore} from '../src/core/auth/store.ts';
import {createOperationsStore,cents} from '../src/core/operations/store.ts';
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'endo-ops-test-'));const path=join(dir,'db.sqlite');const auth=createAuthStore(path);const ceo=auth.bootstrap('CEO','ceo@example.com','Synthetic-password-999');const ops=createOperationsStore(path);t.after(()=>{ops.close();auth.close();rmSync(dir,{recursive:true,force:true});});const save=(module,input)=>ops.mutate(ceo.id,module,{key:randomUUID(),...input});const service=save('servicios',{name:'Consulta de prueba',duration:'30',price:'1000.25'});return {path,auth,ceo,ops,save,service};}
const payment=(service,overrides={})=>({kind:'cobro',amount:'1000.25',date:'2025-01-20',concept:'Pago de prueba',method:'efectivo',service_id:service,...overrides});
test('migración aditiva y persistencia: conserva cuentas, sesiones y registros',t=>{const {path,auth,ceo,ops,save}=fixture(t);const token=auth.login('ceo@example.com','Synthetic-password-999');save('equipo',{name:'Médico prueba',email:'medico@example.com',role:'medico',user_id:''});const reopened=createOperationsStore(path);assert.equal(reopened.list(ceo.id,'equipo').length,1);assert.equal(reopened.list(ceo.id,'servicios').length,1);assert.equal(auth.session(token).id,ceo.id);reopened.close();});
test('importes exactos, idempotencia y transacciones sin doble cobro',t=>{const {ops,ceo,service}=fixture(t);assert.equal(cents('1000.25'),100025);for(const invalid of ['0','-1','1.001','1e3','1,00','NaN'])assert.throws(()=>cents(invalid));const input={...payment(service),key:randomUUID()};const first=ops.mutate(ceo.id,'cobros',input);assert.equal(ops.mutate(ceo.id,'cobros',input),first);assert.throws(()=>ops.mutate(ceo.id,'cobros',{...input,amount:'500'}));assert.equal(ops.list(ceo.id,'cobros').length,1);assert.equal(ops.summary(ceo.id,'2025').net,100025);});
test('devoluciones vinculadas, límite, fecha propia y suma mensual anual',t=>{const {save,service,ops,ceo}=fixture(t);const original=save('cobros',payment(service));save('cobros',{kind:'devolucion',amount:'200.10',date:'2025-02-01',concept:'Devolución parcial',original_id:original});assert.throws(()=>save('cobros',{kind:'devolucion',amount:'900',date:'2025-03-01',concept:'Exceso',original_id:original}));assert.throws(()=>save('cobros',{kind:'devolucion',amount:'1',date:'2025-01-01',concept:'Anterior',original_id:original}));const s=ops.summary(ceo.id,'2025');assert.equal(s.gross,100025);assert.equal(s.refunds,20010);assert.equal(s.net,80015);assert.equal(s.months[1].net,-20010);assert.equal(s.months.reduce((a,m)=>a+m.net,0),s.net);assert.equal(s.methods[0].net,s.net);assert.equal(ops.list(ceo.id,'cobros').length,2);});
test('históricos conservan tarifa, nombre y médico; servicios inactivos no aceptan cobros nuevos',t=>{const {save,service,ops,ceo}=fixture(t);const member=save('equipo',{name:'Médico inicial',email:'doc@example.com',role:'medico',user_id:''});save('cobros',payment(service,{team_id:member}));save('servicios',{id:service,name:'Consulta nueva',duration:'45',price:'2000',active:'0'});save('equipo',{id:member,name:'Médico editado',email:'doc@example.com',role:'medico',user_id:'',active:'0'});const p=ops.list(ceo.id,'cobros')[0];assert.equal(p.service_name,'Consulta de prueba');assert.equal(p.team_name,'Médico inicial');assert.equal(p.amount,100025);assert.throws(()=>save('cobros',payment(service)));});
test('duplicados comerciales, fechas imposibles y fuentes desconocidas',t=>{const {save,ops,ceo}=fixture(t);const input={name:'Prueba',email:'TEST@example.com',phone:'',date:'2025-02-01',channel:'Desconocido',stage:'Nuevo'};save('prospectos',input);assert.throws(()=>save('prospectos',{...input,email:'test@example.com'}));assert.throws(()=>save('prospectos',{...input,email:'other@example.com',date:'2025-02-30'}));assert.equal(ops.summary(ceo.id,'2025').channels[0].channel,'Desconocido');assert.equal(ops.summary(ceo.id,'2024').channels.length,0);});
test('permisos reales por rol y revocación inmediata',t=>{const {auth,ops,ceo,service}=fixture(t);for(const role of ['marketing','administracion','medico','paciente']){const u=auth.create(ceo.id,role,`${role}@example.com`,role);auth.activate(auth.issueToken(ceo.id,u.id),'Synthetic-password-999');if(role==='marketing'){assert.doesNotThrow(()=>ops.list(u.id,'prospectos'));assert.throws(()=>ops.list(u.id,'cobros'));}else if(role==='administracion'){assert.doesNotThrow(()=>ops.list(u.id,'cobros'));assert.throws(()=>ops.list(u.id,'prospectos'));}else{assert.throws(()=>ops.list(u.id,'equipo'));assert.throws(()=>ops.mutate(u.id,'cobros',{...payment(service),key:randomUUID()}));}assert.throws(()=>ops.summary(u.id,'2025'));auth.update(ceo.id,u.id,role,'inactive');assert.throws(()=>ops.list(u.id,'servicios'));}});

test('restauración de una copia consistente conserva movimientos y cuentas',async t=>{const {path,save,service,ceo}=fixture(t);save('cobros',payment(service));const {DatabaseSync}=await import('node:sqlite');const snapshot=path+'.backup';const db=new DatabaseSync(path);db.prepare('VACUUM INTO ?').run(snapshot);db.close();const restoredAuth=createAuthStore(snapshot);const restoredOps=createOperationsStore(snapshot);assert.equal(restoredAuth.list(ceo.id).length,1);assert.equal(restoredOps.summary(ceo.id,'2025').net,100025);restoredOps.close();restoredAuth.close();});
