"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import type {User,Role} from "@/core/auth/store";
import Logout from "@/core/auth/Logout";
const labels:Record<Role,string>={ceo:"Dirección general",medico:"Médico",enfermeria:"Enfermería",administracion:"Administración",marketing:"Marketing",paciente:"Paciente"};
const actions:Record<string,string>={initial_account:"Cuenta inicial creada",login:"Inicio de sesión",logout:"Cierre de sesión",account_created:"Cuenta creada",account_updated_sessions_revoked:"Cuenta actualizada y sesiones cerradas",activation_or_recovery_issued:"Código de acceso generado",password_set:"Contraseña establecida"};
export default function Accounts({users,self,audit}:{users:User[];self:string;audit:{action:string;created:number;actor:string;target:string}[]}){
  const router=useRouter();const[error,setError]=useState("");const[notice,setNotice]=useState("");const[token,setToken]=useState<{value:string;name:string}|null>(null);const[busy,setBusy]=useState(false);
  async function request(action:string,data:object){setBusy(true);setError("");setNotice("");setToken(null);try{const response=await fetch(`/api/auth/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error);router.refresh();return result;}catch(e){setError(e instanceof Error?e.message:"No se pudo conectar.");return null;}finally{setBusy(false);}}
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const result=await request("create",Object.fromEntries(new FormData(form)));if(result){form.reset();setNotice("Cuenta creada, pendiente de activación. Genera su código cuando la persona esté lista para elegir su contraseña.");}}
  return <main className="accounts-page"><header className="accounts-header"><a href="/dashboard">← Dashboard</a><Logout/></header><p className="eyebrow">EL NÚCLEO DE ENDO WOMAN</p><h1>Cuentas y permisos</h1><p>Accesos individuales, administrados por Dirección y verificados en el servidor.</p><section className="panel"><h2>Crear una cuenta</h2><p>No se envía correo automáticamente. Verifica la identidad antes de entregar un código de acceso.</p><form className="account-form" onSubmit={create}><label>Nombre<input name="name" required maxLength={100}/></label><label>Correo<input name="email" type="email" required maxLength={254}/></label><label>Rol<select name="role" defaultValue="medico">{Object.entries(labels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><button disabled={busy} className="primary-button">Crear cuenta</button></form></section>
  {error&&<p className="auth-error" role="alert">{error}</p>}{notice&&<p className="auth-notice" role="status">{notice}</p>}{token&&<section className="panel token-panel" role="status"><h2>Código privado para {token.name}</h2><p>Vence en 30 minutos. Entrega este código únicamente a la persona titular para usarlo en <a href="/activar">Activar mi cuenta</a>. Generarlo cierra sus sesiones anteriores.</p><code>{token.value}</code><button className="logout-button" onClick={()=>setToken(null)}>Ocultar código</button></section>}
  <section className="panel"><h2>Directorio de cuentas</h2><div className="account-list">{users.map(user=><article className="account-row" key={user.id}><div><h3>{user.name} {user.id===self?"(tú)":""}</h3><p>{user.email}</p><span className="soft-tag">{user.status==="active"?"Activa":user.status==="pending"?"Pendiente de activación":"Inactiva"}</span></div><form onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));if(await request("update",{...data,id:user.id}))setNotice("Cuenta actualizada. Sus sesiones anteriores quedaron cerradas.");}}><label>Rol de {user.name}<select name="role" defaultValue={user.role} disabled={user.id===self||busy}>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Estado de {user.name}<select name="status" defaultValue={user.status==="inactive"?"inactive":"active"} disabled={user.id===self||busy}><option value="active">Habilitada</option><option value="inactive">Inactiva</option></select></label><button className="logout-button" disabled={user.id===self||busy}>Guardar cambios</button></form><button className="logout-button" disabled={busy||user.status==="inactive"||user.id===self} onClick={async()=>{const result=await request("token",{id:user.id});if(result)setToken({value:result.token,name:user.name});}}>Generar código de {user.status==="pending"?"activación":"recuperación"}</button></article>)}</div></section>
  <section className="panel"><h2>Permisos de esta etapa</h2><p><b>Dirección:</b> dashboard ejecutivo y administración de cuentas. <b>Otros roles:</b> acceso a su portal inicial. Ningún rol dispone todavía de expedientes clínicos, cobros ni CRM funcionales.</p><p>Al desactivar una cuenta o cambiar su rol se cierran sus sesiones. La desactivación conserva su registro.</p></section>
  <section className="panel"><h2>Actividad de acceso reciente</h2><div className="audit-list">{audit.map((a,i)=><p key={i}><b>{actions[a.action]??a.action}</b> · {a.actor??"Sistema"} → {a.target??"—"}<br/><small>{new Intl.DateTimeFormat("es-MX",{dateStyle:"medium",timeStyle:"short",timeZone:"America/Mexico_City"}).format(a.created)}</small></p>)}</div></section></main>;
}
