"use client";
import { useState, type FormEvent } from "react";
export default function AccessForm({setup=false,activate=false}:{setup?:boolean;activate?:boolean}){
  const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const data=Object.fromEntries(new FormData(e.currentTarget));if((setup||activate)&&data.password!==data.confirm){setError("Las contraseñas no coinciden.");setBusy(false);return;}try{const response=await fetch(`/api/auth/${activate?"activate":setup?"setup":"login"}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error);window.location.assign(result.redirect);}catch(error){setError(error instanceof Error?error.message:"No se pudo conectar.");setBusy(false);}}
  return <main className="access-page"><div className="access-story"><div className="access-logo"><img src="/brand/endo-woman-rosa.png" alt="Endo Woman · Centro ginecológico"/></div><p className="eyebrow">TU ECOSISTEMA ENDO WOMAN</p><h1>Un solo lugar.<br/>Un equipo conectado.</h1><p>El comienzo de una atención que acompaña cada etapa.</p></div><section className="access-card"><p className="eyebrow">{setup?"CONFIGURACIÓN INICIAL LOCAL":activate?"ACTIVACIÓN Y RECUPERACIÓN":"ACCESO INDIVIDUAL"}</p><h2>{setup?"Crea tu cuenta de Dirección":activate?"Elige tu contraseña":"Te damos la bienvenida"}</h2><p>{setup?"Esta será la primera cuenta del ecosistema. Usa una contraseña nueva, exclusiva de Endo Woman.":activate?"Utiliza el código privado que te proporcionó Dirección. Es válido durante 30 minutos y solo puede usarse una vez.":"Ingresa con tu cuenta de Endo Woman. Tus funciones dependen de tu rol."}</p><form onSubmit={submit}>
  {setup&&<label>Tu nombre<input name="name" required maxLength={100} autoComplete="name"/></label>}
  {activate?<label>Código de activación o recuperación<input name="token" required autoComplete="off" maxLength={64}/></label>:<label>Correo<input name="email" type="email" required maxLength={254} autoComplete="username"/></label>}
  <label>{activate?"Nueva contraseña":"Contraseña"}<input name="password" type="password" required minLength={setup||activate?12:1} maxLength={128} autoComplete={setup||activate?"new-password":"current-password"}/></label>
  {(setup||activate)&&<><small>Entre 12 y 128 caracteres.</small><label>Confirmar contraseña<input name="confirm" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label></>}
  {error&&<p className="auth-error" role="alert">{error}</p>}<button className="primary-button" disabled={busy}>{busy?"Procesando…":setup?"Crear cuenta de Dirección":activate?"Guardar contraseña":"Entrar"}</button></form>
  {!setup&&<p><a href={activate?"/acceso":"/activar"}>{activate?"Volver al acceso":"Activar mi cuenta o recuperar acceso"}</a></p>}
  {!setup&&!activate&&<p className="access-help">Si olvidaste tu contraseña, solicita a Dirección un código de recuperación. El envío por correo todavía no está habilitado.</p>}
  <div className="access-footnote">Versión local de desarrollo · Los módulos clínicos y operativos aún están en construcción.</div></section></main>;
}
