import { DatabaseSync } from 'node:sqlite';
import { createHash, randomUUID } from 'node:crypto';
import { resolve } from 'node:path';
export type Module = 'equipo'|'servicios'|'cobros'|'prospectos'|'resumen';
export type Input = Record<string, string>;
export class OperationError extends Error { status:number; constructor(message:string,status=400){super(message);this.status=status;} }
export const access:Record<Module,{read:string[];write:string[]}>= {
  equipo:{read:['ceo','administracion'],write:['ceo']}, servicios:{read:['ceo','administracion'],write:['ceo']},
  cobros:{read:['ceo','administracion'],write:['ceo','administracion']}, prospectos:{read:['ceo','marketing'],write:['ceo','marketing']},
  resumen:{read:['ceo'],write:[]}
};
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Mexico_City',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const clean=(s:string|undefined,max=120,required=true)=>{const v=(s??'').trim();if((required&&!v)||v.length>max)throw new OperationError('Revisa los campos obligatorios y su longitud.');return v;};
export function cents(value:string){if(!/^\d{1,8}(\.\d{1,2})?$/.test(value))throw new OperationError('Escribe un importe válido, con máximo dos decimales.');const [a,b='']=value.split('.');const n=Number(a)*100+Number(b.padEnd(2,'0'));if(n<=0)throw new OperationError('El importe debe ser mayor a cero.');return n;}
function date(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(Date.parse(value))||new Date(value).toISOString().slice(0,10)!==value||value>today())throw new OperationError('La fecha debe ser válida y no estar en el futuro.');return value;}
function oneOf(value:string,values:string[]){if(!values.includes(value))throw new OperationError('Selecciona una opción válida.');return value;}
export function createOperationsStore(path=process.env.ENDOWOMAN_AUTH_DB||resolve('private-data/auth.sqlite')){
  const db=new DatabaseSync(path);db.exec('PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;');
  // Additive, transactional migration: existing accounts and sessions remain intact.
  db.exec(`BEGIN IMMEDIATE;
    CREATE TABLE IF NOT EXISTS op_migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS op_team(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL COLLATE NOCASE UNIQUE,role TEXT NOT NULL,user_id TEXT UNIQUE REFERENCES users(id),active INTEGER NOT NULL CHECK(active IN(0,1)),created_by TEXT NOT NULL REFERENCES users(id));
    CREATE TABLE IF NOT EXISTS op_services(id TEXT PRIMARY KEY,name TEXT NOT NULL COLLATE NOCASE UNIQUE,duration INTEGER NOT NULL CHECK(duration>0),price INTEGER NOT NULL CHECK(price>0),active INTEGER NOT NULL CHECK(active IN(0,1)),created_by TEXT NOT NULL REFERENCES users(id));
    CREATE TABLE IF NOT EXISTS op_payments(id TEXT PRIMARY KEY,date TEXT NOT NULL,kind TEXT NOT NULL CHECK(kind IN('cobro','devolucion')),amount INTEGER NOT NULL CHECK(amount>0),method TEXT NOT NULL CHECK(method IN('efectivo','terminal')),service_id TEXT NOT NULL REFERENCES op_services(id),service_name TEXT NOT NULL,team_id TEXT REFERENCES op_team(id),team_name TEXT NOT NULL,concept TEXT NOT NULL,original_id TEXT REFERENCES op_payments(id),created_by TEXT NOT NULL REFERENCES users(id),CHECK((kind='cobro' AND original_id IS NULL) OR (kind='devolucion' AND original_id IS NOT NULL)));
    CREATE TABLE IF NOT EXISTS op_prospects(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL,phone TEXT NOT NULL,channel TEXT NOT NULL,stage TEXT NOT NULL,date TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id));
    CREATE UNIQUE INDEX IF NOT EXISTS op_prospect_email ON op_prospects(email COLLATE NOCASE) WHERE email!='';
    CREATE UNIQUE INDEX IF NOT EXISTS op_prospect_phone ON op_prospects(phone) WHERE phone!='';
    CREATE INDEX IF NOT EXISTS op_payment_date ON op_payments(date);
    CREATE INDEX IF NOT EXISTS op_payment_original ON op_payments(original_id);
    CREATE TABLE IF NOT EXISTS op_requests(actor TEXT NOT NULL REFERENCES users(id),key TEXT NOT NULL,payload TEXT NOT NULL,result TEXT NOT NULL,PRIMARY KEY(actor,key));
    CREATE TABLE IF NOT EXISTS op_audit(id INTEGER PRIMARY KEY,actor TEXT NOT NULL REFERENCES users(id),module TEXT NOT NULL,action TEXT NOT NULL,target TEXT NOT NULL,before_value TEXT,after_value TEXT NOT NULL,created_at TEXT NOT NULL);
    INSERT OR IGNORE INTO op_migrations VALUES(1,datetime('now'));
    COMMIT;`);
  const rows=(sql:string,...params:(string|number)[])=>db.prepare(sql).all(...params).map(row=>({...row}));
  function permit(actor:string,module:Module,write=false){const u=db.prepare('SELECT role,status FROM users WHERE id=?').get(actor);if(!u||u.status!=='active'||!access[module][write?'write':'read'].includes(String(u.role)))throw new OperationError('No tienes permiso para esta función.',403);}
  function list(actor:string,module:Module){permit(actor,module);switch(module){case 'equipo':return rows('SELECT * FROM op_team ORDER BY name');case 'servicios':return rows('SELECT * FROM op_services ORDER BY name');case 'prospectos':return rows('SELECT * FROM op_prospects ORDER BY date DESC,id');case 'cobros':return rows(`SELECT p.*,u.name AS responsible,COALESCE((SELECT SUM(r.amount) FROM op_payments r WHERE r.original_id=p.id),0) AS refunded FROM op_payments p JOIN users u ON u.id=p.created_by ORDER BY p.date DESC,p.rowid DESC`);default:return [];}}
  function summary(actor:string,year:string){permit(actor,'resumen');if(!/^20\d\d$/.test(year))throw new OperationError('Año no válido.');const months=Array.from({length:12},(_,i)=>({month:i+1,gross:0,refunds:0,net:0,count:0}));for(const r of rows('SELECT substr(date,6,2) AS month,kind,SUM(amount) AS amount,COUNT(*) AS count FROM op_payments WHERE substr(date,1,4)=? GROUP BY month,kind',year)){const m=months[Number(r.month)-1];if(r.kind==='cobro')m.gross+=Number(r.amount);else m.refunds+=Number(r.amount);m.net=m.gross-m.refunds;m.count+=Number(r.count);}return {year,months,gross:months.reduce((a,m)=>a+m.gross,0),refunds:months.reduce((a,m)=>a+m.refunds,0),net:months.reduce((a,m)=>a+m.net,0),team:Number(rows('SELECT COUNT(*) AS n FROM op_team WHERE active=1')[0].n),services:Number(rows('SELECT COUNT(*) AS n FROM op_services WHERE active=1')[0].n),channels:rows('SELECT channel,COUNT(*) AS count FROM op_prospects WHERE substr(date,1,4)=? GROUP BY channel ORDER BY count DESC',year),coverage:rows('SELECT MIN(date) AS first,MAX(date) AS last FROM op_payments WHERE substr(date,1,4)=?',year)[0],methods:rows("SELECT method,SUM(CASE WHEN kind='cobro' THEN amount ELSE -amount END) AS net FROM op_payments WHERE substr(date,1,4)=? GROUP BY method",year)};}
  function mutate(actor:string,module:Module,input:Input){permit(actor,module,true);const key=clean(input.key,80);const payload=createHash('sha256').update(JSON.stringify([module,Object.entries(input).filter(([k])=>k!=='key').sort(([a],[b])=>a.localeCompare(b))])).digest('hex');db.exec('BEGIN IMMEDIATE');try{
    const cached=db.prepare('SELECT payload,result FROM op_requests WHERE actor=? AND key=?').get(actor,key);if(cached){if(cached.payload!==payload)throw new OperationError('Esta solicitud ya fue utilizada con otros datos. Recarga la página.');db.exec('COMMIT');return String(cached.result);}
    const id=input.id||randomUUID();const update=!!input.id;let before:unknown=null;
    if(module==='equipo'){
      const name=clean(input.name);const email=clean(input.email,254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new OperationError('Correo no válido.');const role=oneOf(input.role,['ceo','medico','enfermeria','administracion','marketing']);const userId=input.user_id||null;
      if(userId){const user=db.prepare('SELECT role FROM users WHERE id=?').get(userId);if(!user||user.role==='paciente')throw new OperationError('Selecciona una cuenta del personal.');}
      if(update){before=db.prepare('SELECT * FROM op_team WHERE id=?').get(id);if(!before)throw new OperationError('Integrante no encontrado.',404);db.prepare('UPDATE op_team SET name=?,email=?,role=?,user_id=?,active=? WHERE id=?').run(name,email,role,userId,oneOf(input.active,['0','1']),id);}else db.prepare('INSERT INTO op_team VALUES(?,?,?,?,?,1,?)').run(id,name,email,role,userId,actor);
    }else if(module==='servicios'){
      const name=clean(input.name);if(!/^\d+$/.test(input.duration))throw new OperationError('Duración no válida.');const duration=Number(input.duration);if(duration<5||duration>1440)throw new OperationError('La duración debe estar entre 5 y 1440 minutos.');const price=cents(input.price);
      if(update){before=db.prepare('SELECT * FROM op_services WHERE id=?').get(id);if(!before)throw new OperationError('Servicio no encontrado.',404);db.prepare('UPDATE op_services SET name=?,duration=?,price=?,active=? WHERE id=?').run(name,duration,price,oneOf(input.active,['0','1']),id);}else db.prepare('INSERT INTO op_services VALUES(?,?,?,?,1,?)').run(id,name,duration,price,actor);
    }else if(module==='cobros'){
      if(update)throw new OperationError('Los movimientos no se sobrescriben. Registra una devolución vinculada.');const amount=cents(input.amount);const day=date(input.date);const concept=clean(input.concept,250);const kind=oneOf(input.kind,['cobro','devolucion']);
      if(kind==='devolucion'){
        const original=db.prepare("SELECT * FROM op_payments WHERE id=? AND kind='cobro'").get(input.original_id);if(!original)throw new OperationError('Selecciona el cobro original.');if(day<String(original.date))throw new OperationError('La devolución no puede ser anterior al cobro.');const refunded=Number(db.prepare('SELECT COALESCE(SUM(amount),0) AS n FROM op_payments WHERE original_id=?').get(input.original_id)!.n);if(amount+refunded>Number(original.amount))throw new OperationError('La devolución excede el importe disponible del cobro.');db.prepare('INSERT INTO op_payments VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id,day,kind,amount,original.method,original.service_id,original.service_name,original.team_id,original.team_name,concept,original.id,actor);
      }else{
        const service=db.prepare('SELECT * FROM op_services WHERE id=? AND active=1').get(input.service_id);if(!service)throw new OperationError('Selecciona un servicio activo.');const team=input.team_id?db.prepare("SELECT * FROM op_team WHERE id=? AND active=1 AND role='medico'").get(input.team_id):null;if(input.team_id&&!team)throw new OperationError('Selecciona un médico activo.');const method=oneOf(input.method,['efectivo','terminal']);db.prepare('INSERT INTO op_payments VALUES(?,?,?,?,?,?,?,?,?,?,NULL,?)').run(id,day,kind,amount,method,service.id,service.name,team?.id??null,team?.name??'',concept,actor);
      }
    }else if(module==='prospectos'){
      const name=clean(input.name);const email=clean(input.email,254,false).toLowerCase();const rawPhone=clean(input.phone,30,false);if(rawPhone&&!/^[+\d\s()-]+$/.test(rawPhone))throw new OperationError('Teléfono no válido.');const phone=rawPhone.replace(/[^\d]/g,'');if((!email&&!phone)||(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))||(phone&&(phone.length<10||phone.length>15)))throw new OperationError('Indica un correo o teléfono válido.');const channel=oneOf(input.channel,['Instagram','Google','Facebook','Recomendación','Otro','Desconocido']);const stage=oneOf(input.stage,['Nuevo','Contactado','Interesado','Cerrado']);const day=date(input.date);
      if(update){before=db.prepare('SELECT * FROM op_prospects WHERE id=?').get(id);if(!before)throw new OperationError('Prospecto no encontrado.',404);db.prepare('UPDATE op_prospects SET name=?,email=?,phone=?,channel=?,stage=?,date=? WHERE id=?').run(name,email,phone,channel,stage,day,id);}else db.prepare('INSERT INTO op_prospects VALUES(?,?,?,?,?,?,?,?)').run(id,name,email,phone,channel,stage,day,actor);
    }
    const table={equipo:'op_team',servicios:'op_services',cobros:'op_payments',prospectos:'op_prospects',resumen:''}[module];const after=db.prepare(`SELECT * FROM ${table} WHERE id=?`).get(id);
    db.prepare('INSERT INTO op_audit(actor,module,action,target,before_value,after_value,created_at) VALUES(?,?,?,?,?,?,?)').run(actor,module,update?'editar':'crear',id,before?JSON.stringify(before):null,JSON.stringify(after),new Date().toISOString());db.prepare('INSERT INTO op_requests VALUES(?,?,?,?)').run(actor,key,payload,id);db.exec('COMMIT');return id;
  }catch(error){db.exec('ROLLBACK');if(error instanceof Error && error.message.includes('UNIQUE constraint'))throw new OperationError('Ya existe un registro con ese correo, teléfono, nombre de servicio o cuenta vinculada. Revisa los registros existentes.');throw error;}}
  return {close:()=>db.close(),list,summary,mutate,permit,accounts(actor:string){permit(actor,'equipo',true);return rows("SELECT id,name,role,status FROM users WHERE role!='paciente' ORDER BY name");}};
}
