import Image from 'next/image';
import Logout from '@/core/auth/Logout';
import type { createOperationsStore } from '@/core/operations/store';
type Summary=ReturnType<ReturnType<typeof createOperationsStore>['summary']>;
const money=(n:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n/100);
const months=['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'];
export default function Dashboard({accountName,data}:{accountName:string;data:Summary}){
 const max=Math.max(1,...data.months.map(m=>m.gross));const prospects=data.channels.reduce((a,c)=>a+Number(c.count),0);const channelMax=Math.max(1,...data.channels.map(c=>Number(c.count)));
 return <div className="shell"><aside className="sidebar"><a className="brand" href="/dashboard" aria-label="Endo Woman, dashboard"><Image src="/brand/endo-woman-rosa.png" alt="Endo Woman · Centro ginecológico" width={720} height={720} priority unoptimized/></a><nav aria-label="Navegación del CEO"><a className="accounts-link" href="/dashboard" aria-current="page">Dashboard</a>{[['equipo','Equipo'],['servicios','Servicios'],['cobros','Cobros y devoluciones'],['prospectos','CRM y prospectos']].map(([id,label])=><a className="accounts-link" key={id} href={`/operacion/${id}`}>{label}</a>)}<a className="accounts-link" href="/cuentas">Usuarios y permisos</a></nav><div className="sidebar-bottom"><div className="role-caption">ECOSISTEMA ENDO WOMAN</div><div className="role-badge">Dirección general</div><p>Registros locales</p></div></aside><div className="workspace"><header className="topbar"><span className="portal-chip">Dirección general · CEO</span><div className="profile"><span>{accountName}</span><Logout/></div></header><main>
 <div className="heading"><div><p className="eyebrow">CENTRO GINECOLÓGICO · PUEBLA</p><h1>Tu clínica, en una vista</h1><p className="subtitle">Indicadores calculados desde los registros guardados.</p></div><form className="year-picker" action="/dashboard"><label htmlFor="year">Año de cobros y prospectos</label><input id="year" name="year" type="number" min="2000" max="2099" defaultValue={data.year} required/><button className="logout-button">Consultar</button></form></div>
 <p className="demo-note">Fuente: base operativa local · {data.year}. Los meses sin movimientos indican ausencia de registros; no confirman ausencia de ingresos.</p>
 <section className="cards"><article className="metric-card"><div className="metric-label">Cobros brutos · {data.year}</div><strong>{money(data.gross)}</strong><p>Pagos registrados en efectivo y terminal.</p><div className="card-bottom"><a href="/operacion/cobros">Ver movimientos</a></div></article><article className="metric-card"><div className="metric-label">Cobros netos · {data.year}</div><strong>{money(data.net)}</strong><p>Devoluciones: {money(data.refunds)}. No representa utilidad.</p><div className="card-bottom"><span>Brutos menos devoluciones del periodo</span></div></article><article className="metric-card"><div className="metric-label">Prospectos · {data.year}</div><strong>{prospects}</strong><p>Contactos registrados, sin equivalencia automática a citas.</p><div className="card-bottom"><a href="/operacion/prospectos">Ver prospectos</a></div></article><article className="metric-card"><div className="metric-label">Equipo activo · actual</div><strong>{data.team} <small>personas</small></strong><p>{data.services} servicios activos. Independiente del año consultado.</p><div className="card-bottom"><a href="/operacion/equipo">Ver equipo</a></div></article></section>
 <section className="panel lower-panel"><div className="panel-heading"><div><h2>Evolución de cobros</h2><p>Importes brutos por mes · {data.year} · MXN</p></div><span className="soft-tag">Registros guardados</span></div><div className="chart" role="img" aria-label="Cobros brutos por mes; valores exactos en el desglose inferior.">{data.months.map((m,i)=><div className="bar-col" key={i}><div className="bar-space">{m.count?<><span className="bar-value">{(m.gross/100).toLocaleString('es-MX',{maximumFractionDigits:0})}</span><div className="bar" style={{height:`${m.gross/max*145}px`}}/></>:<span className="no-value">—</span>}</div><span className="month">{months[i]}</span></div>)}</div><p className="demo-note">{data.coverage.first?`Movimientos registrados entre ${data.coverage.first} y ${data.coverage.last}. Esto no acredita cobertura completa del periodo.`:'Todavía no hay movimientos registrados para este año.'}</p><details><summary>Ver desglose mensual y totales</summary><div className="table-wrap"><table><thead><tr><th>Mes</th><th>Brutos</th><th>Devoluciones</th><th>Netos</th></tr></thead><tbody>{data.months.map((m,i)=><tr key={i}><td>{months[i]}{!m.count?' · Sin registros':''}</td><td>{money(m.gross)}</td><td>{money(m.refunds)}</td><td>{money(m.net)}</td></tr>)}</tbody><tfoot><tr><th>Total</th><th>{money(data.gross)}</th><th>{money(data.refunds)}</th><th>{money(data.net)}</th></tr></tfoot></table></div></details></section>
 <section className="two-columns lower-panel"><article className="panel"><h2>Origen de tus prospectos</h2><p>Contactos registrados durante {data.year}</p>{!data.channels.length?<p>No hay prospectos registrados en este año.</p>:<div className="channels">{data.channels.map(c=><div className="channel" key={String(c.channel)}><div><span>{String(c.channel)}</span><strong>{String(c.count)}</strong></div><div className="channel-track"><span style={{width:`${Number(c.count)/channelMax*100}%`}}/></div></div>)}</div>}</article><article className="panel"><h2>Métodos de pago</h2><p>Cobros netos del año seleccionado</p>{!data.methods.length?<p>Sin movimientos registrados.</p>:data.methods.map(m=><p key={String(m.method)}><b>{m.method==='efectivo'?'Efectivo':'Terminal'}:</b> {money(Number(m.net))}</p>)}<p className="demo-note">Terminal indica el método capturado en recepción; la conciliación bancaria se incorporará después.</p></article></section>
 <footer><span>ENDO WOMAN · CENTRO GINECOLÓGICO</span><span>Desarrollo local · Sin conexión a sistemas externos</span></footer></main></div></div>;
}
