"use client";
import {useRef,useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import Logout from '@/core/auth/Logout';
import type {Module} from '@/core/operations/store';
type Row=Record<string,string|number|bigint|null|Uint8Array>;
const titles={equipo:'Equipo',servicios:'Servicios',cobros:'Cobros',prospectos:'Prospectos',resumen:'Resumen'};
const currency=(n:unknown)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(n)/100);
export default function Operations({module,rows,writable,day,accounts,services,team,ceo}:{module:Module;rows:Row[];writable:boolean;day:string;accounts:Row[];services:Row[];team:Row[];ceo:boolean}){
 const router=useRouter();const[editing,setEditing]=useState<Row|null>(null);const[open,setOpen]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);const[kind,setKind]=useState('cobro');const[query,setQuery]=useState('');const key=useRef('');const formRef=useRef<HTMLFormElement>(null);
 function start(row:Row|null=null){setEditing(row);setKind('cobro');setOpen(true);setError('');setNotice('');key.current=crypto.randomUUID();}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const input=Object.fromEntries(new FormData(e.currentTarget));try{const response=await fetch(`/api/operacion/${module}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,key:key.current,...(editing?{id:editing.id}:{})})});const result=await response.json();if(!response.ok)throw new Error(result.error);setOpen(false);setNotice('Registro guardado en la base de datos.');router.refresh();}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}}
 const val=(key:string,fallback='')=>String(editing?.[key]??fallback);
 const field=(name:string,label:string,type='text',required=true,defaultValue=val(name))=><label key={name}>{label}<input name={name} type={type} required={required} defaultValue={defaultValue} maxLength={type==='email'?254:120} max={type==='date'?day:undefined} step={type==='number'?'0.01':undefined}/></label>;
 const select=(name:string,label:string,options:[string,string][],defaultValue=val(name,options[0]?.[0]??''))=><label>{label}<select name={name} defaultValue={defaultValue}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>;
 const active=()=>editing&&select('active','Estado',[['1','Activo'],['0','Inactivo']]);
 const visible=rows.filter(row=>[row.name,row.email,row.phone,row.concept,row.service_name,row.date].some(v=>String(v??'').toLowerCase().includes(query.trim().toLowerCase())));
 return <main className="accounts-page"><header className="accounts-header"><a href={ceo?'/dashboard':'/portal'}>← {ceo?'Dashboard':'Mi portal'}</a><Logout/></header><p className="eyebrow">ENDO WOMAN · REGISTROS LOCALES</p><h1>{titles[module]}</h1><p>{module==='equipo'?'El registro laboral y la cuenta de acceso son independientes. Desactivar un integrante aquí no desactiva su cuenta.':module==='servicios'?'Las tarifas y nombres nuevos no modifican los cobros históricos.':module==='cobros'?'Dinero registrado como cobrado. Terminal no significa depósito bancario conciliado. Las devoluciones se registran por el mismo método del cobro.':'Seguimiento comercial básico. No incluyas información clínica; “Cerrado” no equivale a una consulta realizada.'}</p>
 {writable&&<button className="primary-button" onClick={()=>start()}>+ {module==='cobros'?'Registrar movimiento':'Agregar registro'}</button>}
 {notice&&<p className="auth-notice" role="status">{notice}</p>}
 {open&&<section className="panel"><h2>{editing?'Editar registro':'Nuevo registro'}</h2><form key={String(editing?.id??'new')} ref={formRef} onSubmit={save}><fieldset disabled={busy} className="ops-fields">
 {module==='equipo'&&<>{field('name','Nombre')}{field('email','Correo','email')}{select('role','Función en el equipo',[['medico','Médico'],['enfermeria','Enfermería'],['administracion','Administración'],['marketing','Marketing'],['ceo','Dirección']])}{select('user_id','Cuenta vinculada (opcional)',[['','Sin cuenta vinculada'],...accounts.map(r=>[String(r.id),String(r.name)] as [string,string])])}{active()}</>}
 {module==='servicios'&&<>{field('name','Nombre del servicio')}{field('duration','Duración en minutos','number',true,val('duration','30'))}{field('price','Tarifa MXN','number',true,editing?String(Number(editing.price)/100):'')}{active()}</>}
 {module==='prospectos'&&<>{field('name','Nombre')}{field('email','Correo (o teléfono)','email',false)}{field('phone','Teléfono (o correo)','tel',false)}{field('date','Fecha de registro','date',true,val('date',day))}{select('channel','Origen',[...['Desconocido','Instagram','Google','Facebook','Recomendación','Otro'].map(v=>[v,v] as [string,string])])}{select('stage','Etapa',[...['Nuevo','Contactado','Interesado','Cerrado'].map(v=>[v,v] as [string,string])])}</>}
 {module==='cobros'&&<><label>Tipo de movimiento<select name="kind" value={kind} onChange={e=>setKind(e.target.value)}><option value="cobro">Cobro</option><option value="devolucion">Devolución</option></select></label>{field('date','Fecha del movimiento','date',true,day)}{field('amount','Importe MXN','number')}{field('concept',kind==='cobro'?'Concepto / referencia interna':'Motivo de devolución')}{kind==='cobro'?<>{select('service_id','Servicio',[['','Seleccionar'],...services.filter(r=>r.active===1).map(r=>[String(r.id),`${r.name} · ${currency(r.price)}`] as [string,string])])}{select('team_id','Médico asociado',[['','Sin médico asociado'],...team.filter(r=>r.active===1&&r.role==='medico').map(r=>[String(r.id),String(r.name)] as [string,string])])}{select('method','Método de pago',[['efectivo','Efectivo'],['terminal','Terminal']])}</>:select('original_id','Cobro original',[['','Seleccionar'],...rows.filter(r=>r.kind==='cobro'&&Number(r.amount)>Number(r.refunded)).map(r=>[String(r.id),`${r.date} · ${r.concept} · disponible ${currency(Number(r.amount)-Number(r.refunded))}`] as [string,string])])}</>}
 </fieldset>{error&&<p className="auth-error" role="alert">{error}</p>}<div className="form-actions"><button disabled={busy} className="primary-button">{busy?'Guardando…':'Guardar'}</button><button type="button" disabled={busy} className="logout-button" onClick={()=>setOpen(false)}>Cancelar</button></div></form></section>}
 <section className="panel"><h2>Registros guardados</h2><label className="ops-search">Buscar<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre, concepto o fecha"/></label><p>{visible.length} de {rows.length} registros</p>{!visible.length?<p>No hay registros que mostrar.</p>:<div className="ops-list">{visible.map(row=><article className="ops-row" key={String(row.id)}><div><h3>{String(row.name??row.concept)}</h3>{module==='equipo'&&<p>{String(row.email)} · {String(row.role)} · {row.active?'Activo':'Inactivo'}</p>}{module==='servicios'&&<p>{currency(row.price)} · {String(row.duration)} minutos · {row.active?'Activo':'Inactivo'}</p>}{module==='prospectos'&&<p>{String(row.email||row.phone)} · {String(row.channel)} · {String(row.stage)} · {String(row.date)}</p>}{module==='cobros'&&<><p><b>{row.kind==='devolucion'?'Devolución':'Cobro'}: {currency(row.amount)}</b> · {String(row.method)} · {String(row.date)}</p><p>{String(row.service_name)} · {String(row.team_name||'Sin médico asociado')} · Registró: {String(row.responsible)}</p><small>Referencia: {String(row.id)}{row.original_id?` · Cobro original: ${row.original_id}`:''}</small></>}</div>{writable&&module!=='cobros'&&<button className="logout-button" onClick={()=>start(row)}>Editar</button>}</article>)}</div>}</section><p className="local-notice">Base local de desarrollo. Estos registros todavía no sustituyen la operación clínica ni se sincronizan entre computadoras.</p></main>;
}
